apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-grainstorage.fullname" . }}
  labels:
    {{- include "comax-grainstorage.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "comax-grainstorage.selectorLabels" . | nindent 4 }}
