apiVersion: v1
kind: Service
metadata:
  name: {{ include "comax-mariadb.fullname" . }}
  labels:
    {{- include "comax-mariadb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: svcport
  selector:
    {{- include "comax-mariadb.selectorLabels" . | nindent 4 }}
