apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "comax-orchestrator.secretName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "comax-orchestrator.serviceAccountName" . }}
data:
  OIDC__Secret: {{ .Values.oidc.secret | b64enc }}
  OIDC__GrainStorageSecret: {{ .Values.oidc.grainStorageSecret | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPassword | b64enc }}
  MYSQL_PASSWORD: {{ .Values.db.password | b64enc }}