apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentsilos.communaxiom.org
spec:
  group: communaxiom.org
  names:
    kind: AgentSilo
    listKind: AgentSiloList
    plural: agentsilos
    singular: agentsilo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              currentState:
                type: string
              stateTsMs:
                format: int64
                type: integer
              stateTs:
                format: int64
                type: integer
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              image:
                type: string
              storeApiImage:
                type: string
              mariadbImage:
                type: string
              oidcAuthority:
                type: string
              oidcClientId:
                type: string
              oidcSecretName:
                type: string
              oidcSecretKey:
                type: string
              membershipAddress:
                type: string
              clusterId:
                type: string
              serviceId:
                type: string
              siloPort:
                type: string
              gatewayPort:
                type: string
              commonsMembership:
                type: string
              dbCredSecretName:
                type: string
              dbCredUsernameKey:
                type: string
              dbCredPasswordKey:
                type: string
              dbCredRootPasswordKey:
                type: string
              resources:
                nullable: true
                properties:
                  claims:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    type: array
                  limits:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - DecimalExponent
                          - BinarySI
                          - DecimalSI
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                  requests:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - DecimalExponent
                          - BinarySI
                          - DecimalSI
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                type: object
              environmentVariables:
                items:
                  properties:
                    name:
                      type: string
                    value:
                      type: string
                    valueFrom:
                      properties:
                        configMapKeyRef:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                        fieldRef:
                          properties:
                            apiVersion:
                              type: string
                            fieldPath:
                              type: string
                          type: object
                        resourceFieldRef:
                          properties:
                            containerName:
                              type: string
                            divisor:
                              properties:
                                format:
                                  enum:
                                  - DecimalExponent
                                  - BinarySI
                                  - DecimalSI
                                  type: string
                                value:
                                  type: string
                              type: object
                            resource:
                              type: string
                          type: object
                        secretKeyRef:
                          properties:
                            key:
                              type: string
                            name:
                              type: string
                            optional:
                              nullable: true
                              type: boolean
                          type: object
                      type: object
                  type: object
                type: array
              annotations:
                additionalProperties:
                  type: string
                type: object
              labels:
                additionalProperties:
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}