apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: comaxcomclients.communaxiom.org
spec:
  group: communaxiom.org
  names:
    kind: ComaxCommonsClient
    listKind: ComaxCommonsClientList
    plural: comaxcomclients
    singular: comaxcommonsclient
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              currentState:
                type: string
              stateTsMs:
                format: int64
                type: integer
              stateTs:
                format: int64
                type: integer
              clusterState:
                additionalProperties:
                  type: string
                type: object
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              ingressHost:
                type: string
              ingressCertManager:
                type: string
              ingressCertSecret:
                type: string
              useHttps:
                type: boolean
              oidcAuthority:
                type: string
              oidcClientId:
                type: string
              oidcSecretName:
                type: string
              oidcSecretKey:
                type: string
              commonsClientImage:
                type: string
              commonsMembershipHost:
                type: string
              commonsMembershipCacheDuration:
                type: string
              clusterId:
                type: string
              serviceId:
                type: string
              resources:
                nullable: true
                properties:
                  claims:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    type: array
                  limits:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - DecimalExponent
                          - BinarySI
                          - DecimalSI
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                  requests:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - DecimalExponent
                          - BinarySI
                          - DecimalSI
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                type: object
              labels:
                additionalProperties:
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}