apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: comaxagents.communaxiom.org
spec:
  group: communaxiom.org
  names:
    kind: ComaxAgent
    listKind: ComaxAgentList
    plural: comaxagents
    singular: comaxagent
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              currentState:
                type: string
              stateTsMs:
                format: int64
                type: integer
              stateTs:
                format: int64
                type: integer
              clusterState:
                additionalProperties:
                  type: string
                type: object
              agentRefereeName:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              ingressHost:
                type: string
              ingressCertManager:
                type: string
              ingressCertSecret:
                type: string
              useHttps:
                type: boolean
              oidcAuthority:
                type: string
              oidcClientId:
                type: string
              oidcSecretName:
                type: string
              oidcSecretKey:
                type: string
              commonsClientImage:
                type: string
              refereeImage:
                type: string
              agentSiloImage:
                type: string
              storeApiImage:
                type: string
              mariadbImage:
                type: string
              membershipAddress:
                type: string
              clusterId:
                type: string
              serviceId:
                type: string
              siloPort:
                type: string
              gatewayPort:
                type: string
              dbCredSecretName:
                type: string
              dbCredUsernameKey:
                type: string
              dbCredPasswordKey:
                type: string
              dbCredRootPasswordKey:
                type: string
              labels:
                additionalProperties:
                  type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}