apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comax-referee.fullname" . }}
  labels:
    {{- include "comax-referee.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "comax-referee.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "comax-referee.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "comax-referee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: {{ .Values.pvcName }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.orch.gatewayport }}
              protocol: TCP
          volumeMounts:
          - name: datastore
            mountPath: "/data"
          env:
          - name: OIDC__Authority
            value: {{ .Values.oidc.auth }}
          - name: OIDC__Scopes
            value: {{ .Values.oidc.scopes }}
          - name: OIDC__ClientId
            value: {{ .Values.oidc.clientId }}
          - name: OIDC__Secret
            valueFrom:
              secretKeyRef:
                name: {{ include "comax-referee.secretName" . }}
                key: OIDC__Secret
          - name: LiteDbStorage__FileName
            value: /data/SiloStore.db
          - name: JObjectStore__FileName
            value: /data/SiloStore.db
          - name: PubSubStore__FileName
            value: /data/PubSubStore.db
          - name: CentralApiUrl
            value: {{ .Values.centralApiUrl }}
          - name: siloPort
            value: "7718"
          - name: gatewayPort
            value: "30001"
          - name: advertisedIp
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     scheme: HTTP
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
