// <auto-generated />
using System;
using GrainStorageService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrainStorageService.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20230211134156_initiial")]
    partial class initiial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GrainStorageService.Models.StandardStorage", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("EntityType", "Id");

                    b.HasIndex(new[] { "EntityType", "Id", "LastModifiedDate" }, "LookupIndex")
                        .IsDescending(false, false, true);

                    b.ToTable("StandardStorage", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
