name: Agent Referee Build

env:
  VERSION: 0.0.1

on:
  workflow_dispatch:
    inputs: 
      version:
        required: true
        default: 0.0.1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Docker Build & Push Action
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@0e68818ea37ba7728f417f03a58e06e68d9d2592
      uses: docker/build-push-action@v4
      with:
        # Name of the Docker image
        image: vertechcon/agentreferee
        # Tags override for Docker image
        tags: ${{ github.event.inputs.version }}-alpine # optional
        # Location of Dockerfile, if not Dockerfile in root directory
        file: agent-referee.Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        pushImage: true 
    
